name: IssueCraft

on:
  issues:
    types: [opened]

jobs:
  enhance-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: nameless-traveler/issuecraft@v1.0.0
        env:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
